version: "3"

volumes:
  db:

services:
  web:
    build: .
    image: quangtd95/ktor-gpt:1.3.0
    environment:
      - OPENAI_TOKEN=${OPENAI_TOKEN}
      - DATABASE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}?user=${POSTGRES_PASSWORD}&password=${POSTGRES_USER}
    ports:
      - "8989:8989"
    depends_on:
      db:
        condition: service_healthy
  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gpt" ]
      interval: 1s
